#version 430 core

layout(local_size_x = 16, local_size_y = 16) in;

layout(binding = 0, rgba32f) uniform image2D diffuseTexture;
layout(binding = 1, r32f) uniform image2D thicknessTexture;
layout(binding = 2, rgba32f) uniform image2D outputTexture;

uniform vec3 ssTint;

void main() {
    ivec2 px = ivec2(gl_GlobalInvocationID.xy);

    vec3 orgCol = mix(imageLoad(diffuseTexture, px).rgb, ssTint, imageLoad(thicknessTexture, px).r);

    imageStore(outputTexture, px, vec4(orgCol, 1.0));
}